### ISSUE TITLE
My all commits are following conventional commit format but the `Semantic PRS` github app is showing error

### ISSUE THREAD

**Issue by aayushchugh** [Ezard/semantic-prs#105]
![image](https://user-images.githubusercontent.com/69336518/183920574-81bb0ef9-ce38-446c-8f6a-3067997063f2.png)

I think that this problem is due to scopes when I don't use scopes than it is working fine

![image](https://user-images.githubusercontent.com/69336518/183920870-462cb3e6-4e73-48e3-9c00-9974e7d00df9.png)

**Comment by Ezard** [comment]
@aayushchugh apologies for the slow reply; could you paste your `semantic.yml` config here please? (if you have setup a custom config)

**Comment by aayushchugh** [comment]
@Ezard I don't have any config file

**Comment by Ezard** [comment]
@aayushchugh I've tried to reproduce the issue based on your attached image, but I'm not able to so far
Could you comment here with the title of the PR, along with the list of commit messages, that caused the failure please?

**Comment by aayushchugh** [comment]
here is the link for pull request you can check all of that here
this one is messy because I was testing all my github apps on this pr

https://github.com/shriproperty/admin-app/pull/19

**Comment by Ezard** [comment]
@aayushchugh so there seem to be a couple of things at play here:
1. if a commit message or a PR starts with an emoji, then it is not classed as being semantic. An emoji can be somewhere that isn't at the start though (e.g. `bug(foo): 🐛 do some stuff` is semantic, but `🐛 bug(foo): do some stuff` is not semantic). If you want to include emoji at the start or PRs/commit messages then you can use the `types` field in the config to specify your own list of types (e.g. `🐛 bug` instead of the default `bug`)
2. By default, the app makes sure that either the title is semantic, or _all_ commits are semantic; since the title wasn't semantic (due to the above emoji issue), and your first commit message (`Started working on #13`) wasn't semantic, the app said that your PR wasn't semantic. You can change this behaviour by updating the config to tell the app to only check the title (`titleOnly: true`), or to only make sure that at least 1 commit semantic (`anyCommit: true`). Note that if you set `anyCommit` to `true`, then you will also need to set either `commitsOnly` or `titleAndCommits` to `true`
3. 
Hope this helps, but let me know if you'd like any more info!

**Comment by aayushchugh** [comment]
Yup, I got it now. anyways this issue is 19 days old. when I just learnt about conventional commits
but now I don't get any issue like this in my repo

btw I have developed my own github app for some automation inspired by this one can you
please give me some feedback about it
[Repository Commander](https://github.com/marketplace/shriproperty-bot)

**Comment by aayushchugh** [comment]
And I would like to contribute in your app any issues for me ?

**Comment by Ezard** [comment]
@aayushchugh your app looks cool!

And thanks for the offer of help - there aren't any open issues atm, but keep an eye on the repo in case anything pops up!

**Comment by aayushchugh** [comment]
@Ezard Thank's for your time and help
