### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by ChipWolf** [Ezard/semantic-prs#18]
Hey, thanks for this drop-in replacement for Semantic Pull Requests!

The only issue we have is that the check doesn't appear to run in our private repositories, I'm guessing this isn't intentional behaviour?

Thanks

**Comment by Ezard** [comment]
@ChipWolf my assumption is that this is because the app is still going through the GitHub Marketplace review - it also doesn't work yet on the (private) repos of the company that I work for

So does it work on public repos then, or have you not tested that? I know that it works on my own personal public repos (such as this one) which makes sense, but if it works on your public repos then I'd be surprised haha (since I assume it has to be approved by GitHub before anyone other than me can make use of it)

As you mentioned though, this isn't intentional behaviour - it should work everywhere 🙂

**Comment by ChipWolf** [comment]
<img width="959" alt="Screenshot 2022-05-10 at 16 26 33" src="https://user-images.githubusercontent.com/3164166/167665227-c07edf50-7c20-45ad-9fd6-83968da9f673.png">

Appears to run fine in our public repos

**Comment by Ezard** [comment]
@ChipWolf I think I figured out the issue - the app wasn't able to read the contents of `.github/semantic.yml`, so was erroring

You should get an email about an updated permissions request that will allow the app to read that file, so fingers crossed that resolves the issue 🤞

**Comment by Ezard** [comment]
Can confirm that the check is now appearing on private repos for me - thanks for poking me to look into this! (since I would've just waited for approval instead)
