### ISSUE TITLE
Plugin does not recognise dependabots Build as a valid pr title

### ISSUE THREAD

**Issue by DebkanchanSamadder** [Ezard/semantic-prs#319]
### Describe the bug

dependabot sometimes creates pr that start with "Build" which is valid according to conventional commit spec but semantic pr always fails for those prs

### semantic.yml contents

```yml

```

### Sample PR Title(s) (if relevant)

Build(deps-dev): Bump typescript from 5.0.4 to 5.1.3

**Comment by Ezard** [comment]
@DebkanchanSamadder that specific example fails the check because `Build` is not all lowercase - if you use `build` instead then the check will pass

If you want to keep that capitalisation then you can set `types` in `semantic.yml` ([see readme](https://github.com/Ezard/semantic-prs#configuration-options)) to be `Feat`, `Fix`, `Build`, etc, or whatever you want 🙂

**Comment by DebkanchanSamadder** [comment]
I added the following to my org's .github repo's semantic.yml but it still doesn't work
```yaml
types:
  - Build
  ````

**Comment by Ezard** [comment]
@DebkanchanSamadder did you put it in the `.github` directory inside your org's `.github` repo?

i.e. if you visit `https://github.com/<your org name>/.github/blob/master/.github/semantic.yml` then can you see the file?

Looking at the logs, assuming the org that you're talking about is the one from your GitHub profile, then I can see 404 errors when the app is searching for the `semantic.yml` file, for both your org and for specific repos

**Comment by DebkanchanSamadder** [comment]
I forgot to put it inside .github directory. Now it works fine. Thank you very much.
